const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Button,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Behaviors.custom,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.SetLayoutEffectEnabled,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Acts.SetLayoutEffectParam,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.custom.Acts.Accelerate,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.LocalStorage.Acts.SetItem
	];
};
self.C3_JsPropNameTable = [
	{Bullet: 0},
	{DataCoin: 0},
	{Touch: 0},
	{TopSpawner: 0},
	{TimeUp: 0},
	{Timer: 0},
	{TimeDown: 0},
	{Background1: 0},
	{MainScreen: 0},
	{Spin: 0},
	{Small: 0},
	{Player1: 0},
	{Keyboard: 0},
	{DistanceDisplay: 0},
	{Sine: 0},
	{Virus1: 0},
	{Button: 0},
	{BottomSpawner: 0},
	{Block: 0},
	{Big: 0},
	{Story: 0},
	{Gameover: 0},
	{HomeButton: 0},
	{BestScore: 0},
	{Fade: 0},
	{SkipButton: 0},
	{Player2: 0},
	{Background2: 0},
	{Virus2: 0},
	{ChooseScreen: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{Virus5: 0},
	{Virus6: 0},
	{Player3: 0},
	{Background3: 0},
	{Virus3: 0},
	{Virus7: 0},
	{Sine2: 0},
	{Custom: 0},
	{Character: 0},
	{Bullet2: 0},
	{Back: 0},
	{Enemy: 0},
	{Item: 0},
	{Click: 0},
	{TotalDistance: 0},
	{NextBlockX: 0},
	{TopSpawnerTargetY: 0},
	{BottomSpawnerTargetY: 0},
	{GameOver: 0},
	{CreateCharacter: 0},
	{EnemyCreate: 0},
	{ScreenEffect: 0},
	{CurrentTime: 0},
	{TimeLimit: 0},
	{BGM: 0},
	{Sound: 0},
	{Type: 0}
];

self.InstanceType = {
	DataCoin: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TopSpawner: class extends self.ISpriteInstance {},
	TimeUp: class extends self.ISpriteInstance {},
	Timer: class extends self.ITextInstance {},
	TimeDown: class extends self.ISpriteInstance {},
	Background1: class extends self.ITiledBackgroundInstance {},
	MainScreen: class extends self.ISpriteInstance {},
	Spin: class extends self.ISpriteInstance {},
	Small: class extends self.ISpriteInstance {},
	Player1: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	DistanceDisplay: class extends self.ITextInstance {},
	Virus1: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	BottomSpawner: class extends self.ISpriteInstance {},
	Block: class extends self.ITiledBackgroundInstance {},
	Big: class extends self.ISpriteInstance {},
	Story: class extends self.ISpriteInstance {},
	Gameover: class extends self.ISpriteInstance {},
	HomeButton: class extends self.ISpriteInstance {},
	BestScore: class extends self.ITextInstance {},
	Fade: class extends self.ISpriteInstance {},
	SkipButton: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	Background2: class extends self.ITiledBackgroundInstance {},
	Virus2: class extends self.ISpriteInstance {},
	ChooseScreen: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Virus5: class extends self.ISpriteInstance {},
	Virus6: class extends self.ISpriteInstance {},
	Player3: class extends self.ISpriteInstance {},
	Background3: class extends self.ITiledBackgroundInstance {},
	Virus3: class extends self.ISpriteInstance {},
	Virus7: class extends self.ISpriteInstance {},
	Character: class extends self.ISpriteInstance {},
	Back: class extends self.ITiledBackgroundInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Item: class extends self.ISpriteInstance {},
	Click: class extends self.ISpriteInstance {}
}